spring.datasource.url=jdbc:postgresql://localhost:5432/chetya
spring.datasource.username=postgres
spring.datasource.password=chetan
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8085


